### ISSUE TITLE
ActionExecutor.prototype.enqueue to accept Array as first parameter

### ISSUE THREAD

**Issue by danielepiccone** [One-com/action-executor#2]
There is a case in which I would like to populate the queue with a set of actions to be executed sequentially, for example when in a login sequence we need to gather data from different endpoints.

Wondering if something like this could be nice to have in the actionExecutor:

`ActionExecutor.prototype.enqueue = function (serie<Array>, fn<Function>);`

Where serie is an Array of actions, and fn is a callback executed when the current queue is drained.

Ideally we should be able to pass states between functions using the callback on the _execute_ method.

**Comment by mwoc** [comment]
Could be achieved by making a wrapper action, that executes some other actions inside itself, e.g. using async.js, but indeed might be valuable to have this built-in so you don't have to re-invent the wheel as a consumer of ActionExecutor.

**Comment by sunesimonsen** [comment]
I have no problem with this change, but it would also be simple to orchestrate it using async or promises as actions are added to the queue in sync and you just need to listen for when all of them has been executed.

**Comment by gustavnikolaj** [comment]
I feel like this is something that is probably better solved with tools for flow control, rather than on-boarding those features into the library.

Granted, I haven't worked a whole lot with the action executor, but couldn't you either use something like async, as mentioned before, or make a meta action that will enqueue the other actions that you need to be executed?

If there's a good reason why this needs to be solved by the ActionExecutor, then sure - go ahead. But I feel that this is going into territory that should be handled by specific tools.

**Comment by danielepiccone** [comment]
Yes, the meta action and async solve the problem just fine.
I believe the problem to be more app-specific than related to the action-executor way of using the queue, which I understand to be used specifically for retrying, locking and such.
Thanks for the feedback :+1:
